auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            V2Optimization.github.com
url:              http://V2Optimization.github.com
feed:             /atom.xml
author:
    name:         V2Optimization
    twitter:      
description:      "V2Optimization\'s Blog"
author_info:      <a href="http://V2Optimization.github.com/about">V2Optimization</a>

copyright:
    - Design by <a href="http://V2Optimization.github.com/about" title="V2Optimization" target="_blank">V2Optimization</a> &copy; 2013
